// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace UnitPacking
{
    public class UnitPackingOutputs: SystemResults
    {
		/// <summary>
		/// The number of solutions.
		/// </summary>
		[JsonProperty("Number of Solutions")]
		public double NumberOfSolutions { get; set; }

        /// <summary>
        /// Construct a UnitPackingOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public UnitPackingOutputs() : base()
        {
        }

        /// <summary>
        /// Construct a UnitPackingOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public UnitPackingOutputs(double numberOfSolutions) : base()
        {
			this.NumberOfSolutions = numberOfSolutions;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}